title: Van Anh Do # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Fresh graduate experienced in Client Relationship Management and Market Research in Sales Training and Banking industries.
  <br><br>
   Competent with reporting tasks, skilled in business analytics with MS Excel, Google Sheets, Tableau and SQL and having basic knowledge of data analysts with Python. Interested in Business Analytics and Data Analyst. 
  <br><br>
  <a href="https://www.linkedin.com/in/van-anh-do/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
